// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args[0]);

		int countAbove = 0;
		int countBelow = 0;

		for (int i = 0; i < N; i++) {
			double x = Math.random();
			if (x > 0.5) {
				countAbove++;
			} else {
				countBelow++;
			}

		System.out.println(" >0.5: " + countAbove + "times");
		System.out.println(" <=0.5: " + countBelow + "times");
		
		if(countAbove == 0 || countBelow == 0) {
		}
		else {
			double ratio = (double) countAbove / countBelow;
			System.out.println(" Ratio: " + ratio);
		}
	}

	}



}
